---
- name: Install SQL Server tools and dependencies
  hosts: localhost
  become: yes
  tasks:
    - name: Add Microsoft GPG key for Ubuntu < 24.04
      ansible.builtin.command:
        cmd: curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc
      when: ansible_distribution_release in ["bionic", "focal", "jammy"]

    - name: Add Microsoft GPG key for Ubuntu >= 24.04
      ansible.builtin.command:
        cmd: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
      when: ansible_distribution_release in ["lunar", "mantic"]

    - name: Add Microsoft package repository
      ansible.builtin.command:
        cmd: curl https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_release }}/prod.list | tee /etc/apt/sources.list.d/mssql-release.list

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install msodbcsql18
      ansible.builtin.apt:
        name: msodbcsql18
        state: present
        allow_unauthenticated: yes
        install_recommends: no
        default_release: "ACCEPT_EULA=Y"

    - name: Install mssql-tools18 (optional)
      ansible.builtin.apt:
        name: mssql-tools18
        state: present
        allow_unauthenticated: yes
        install_recommends: no
        default_release: "ACCEPT_EULA=Y"

    - name: Update PATH for mssql-tools18 (optional)
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: 'export PATH="$PATH:/opt/mssql-tools18/bin"'
        state: present

    - name: Source .bashrc to apply changes (optional)
      ansible.builtin.shell: source ~/.bashrc
      args:
        executable: /bin/bash

    - name: Install unixodbc-dev (optional)
      ansible.builtin.apt:
        name: unixodbc-dev
        state: present
